// <auto-generated />
using DonkeyDBMigrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DonkeyDBMigrations.Migrations
{
    [DbContext(typeof(DonkeyContext))]
    [Migration("20201201221831_Db-Create")]
    partial class DbCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DonkeyDBMigrations.ModelDonkeyData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Angle")
                        .HasColumnType("REAL");

                    b.Property<double>("Throttle")
                        .HasColumnType("REAL");

                    b.Property<ulong>("TimeStamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Donkeys");
                });
#pragma warning restore 612, 618
        }
    }
}
